name: mt_carplay
description: Flutter Apps are now on Apple CarPlay and Android Auto. This package aims to make it safe to use apps made with Flutter in the car by integrating with CarPlay or Android Auto.
version: 1.2.11
homepage: https://github.com/mobitouchOS/mt_carplay#readme
repository: https://github.com/mobitouchOS/mt_carplay
issue_tracker: https://github.com/mobitouchOS/mt_carplay/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlugin
      android:
        package: net.mobitouch.mt_android_auto
        pluginClass: FlutterAndroidAutoPlugin
